#FROM balenalib/raspberry-pi-python
FROM balenalib/raspberry-pi-alpine-python:latest
#FROM resin/%%RESIN_MACHINE_NAME%%-python

ENV INITSYSTEM on

COPY ./requirements.txt /requirements.txt

RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python", "gpio.py"]