FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-run
ENV INITSYSTEM on

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python", "gpio.py"]