#!/bin/bash
sudo aptitude update
sudo aptitude -y install python-pip libminiupnpc-dev libqt4-dev xvfb
sudo pip install daemonize gpio

sudo rm -rf /usr/share/trezarpi/
wget https://github.com/mkapusnik/gpio/releases/download/tzc/trezarpi.tar.gz
sudo tar -C / -xzf trezarpi.tar.gz
sudo ln -s /usr/share/trezarpi/trezard /etc/init.d/trezard
sudo update-rc.d trezard defaults

#autostart
grep -q -F 'trezarcoin' ~/.config/lxsession/LXDE-pi/autostart || echo "@trezarcoin" >> ~/.config/lxsession/LXDE-pi/autostart

sudo nano /etc/trezard.conf
sudo reboot