#!/bin/bash
echo " ##### Installing dependencies ##### "
sudo aptitude update
sudo aptitude -o Dpkg::Progress-Fancy="1" -y install python-pip libminiupnpc-dev libqt4-dev Xvfb x11vnc expect 
sudo pip install daemonize gpio

echo " ##### Downloading TrezarPi ##### "
sudo rm -rf /usr/share/trezarpi/
sudo rm -rf trezarpi.tar.gz
wget https://github.com/mkapusnik/gpio/releases/download/tzc/trezarpi.tar.gz

echo " ##### Extracting TrezarPi ##### "
sudo tar -C / -xzf trezarpi.tar.gz

echo " ##### Installing services into the OS ##### "
chmod +x /usr/bin/trezarcoin-qt
sudo chown root:root /etc/rc.local
sudo chmod 755 /etc/rc.local
sudo ln -sf /usr/share/trezarpi/trezard /etc/init.d/trezard
sudo update-rc.d trezard defaults

echo " ##### Setting up autostart ##### "
sed -i '/trezarcoin/d' ~/.config/lxsession/LXDE-pi/autostart
echo "@/usr/share/trezarpi/trezarcoin" >> ~/.config/lxsession/LXDE-pi/autostart

#sudo nano /etc/trezarpi.conf
sudo reboot