#!/bin/sh

### BEGIN INIT INFO
# Provides:          trezard
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Trezar Wallet daemon
# Description:       This daemon monitors the state of the TZC wallet
### END INIT INFO

# Author: Michal Kapusnik <michal.kapusnik@gmail.com>

TPI=/usr/share/trezarpi/trezarpi
PIDFILE=/var/run/tpi.pid
case "$1" in
  start)
    echo -n "Starting TZC Wallet daemon"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $TPI
    echo "."
    ;;
  stop)
    echo -n "Stopping virtual X frame buffer: Xvfb"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/trezarpid {start|stop|restart}"
    exit 1
esac

exit 0
