#!/bin/sh

### BEGIN INIT INFO
# Provides:          trezard
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Trezar Wallet daemon
# Description:       This daemon monitors the state of the TZC wallet
### END INIT INFO

# Author: Michal Kapusnik <michal.kapusnik@gmail.com>

case "$1" in
  start)
     /usr/share/trezarpi/lcd Initializing  
     /usr/share/trezarpi/trezard.py start
   ;;
  stop)
    /usr/share/trezarpi/lcd Shutting down
   ;;
  force-reload|restart)
   ;;
  status)
   ;;
 *)
   echo "Usage: /etc/init.d/trezard {start|stop|restart|force-reload|status}"
   exit 1
  ;;
esac

exit 0
