#!/bin/bash
/usr/share/trezarpi/lcd Waiting for USB
while [ $(find /media/pi -mindepth 1 -maxdepth 1 -type d | wc -l) -eq 0 ]; do sleep 2; done
dir=$(find /media/pi -mindepth 1 -maxdepth 1 -type d)
/usr/share/trezarpi/lcd Starting Wallet
trezarcoin-qt -datadir=$dir -conf=$dir/trezarcoin.conf